@startuml

actor Administratius #FF0000/FFFF00
actor Xofer #62AA1A
actor Gerent #0E3250

rectangle Taxis {
    
    usecase "Donar d'alta" as donaAlta
    usecase "Alta Reserves" as altaReserves
    usecase "Cancelar i Confirmar" as cancelaConfirmar
    usecase "Consultar Reserves" as consultarReserves

    donaAlta ..> altaReserves : include
    donaAlta ..> DadesObligatories : extend

    rectangle DadesObligatories {
        usecase "Dades Obligatories" as dob
    }
}


Administratius --> donaAlta
Administratius --> cancelaConfirmar
Administratius --> altaReserves : Si no existeix\ndonarlo dalta directament

Gerent --> donaAlta
Xofer --> consultarReserves

@enduml
